#pragma config(Sensor, in1,    LINE_L,         sensorReflection)
#pragma config(Sensor, in2,    LINE_C,         sensorReflection)
#pragma config(Sensor, in3,    LINE_R,         sensorReflection)
#pragma config(Sensor, in5,    ANGLE_POT,      sensorPotentiometer)
#pragma config(Sensor, in6,    GYRO,           sensorGyro)
#pragma config(Sensor, dgtl1,  QUAD_R,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  QUAD_L,         sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  ULTRA,          sensorSONAR_cm)
#pragma config(Sensor, dgtl11, QUAD_SLIDE,     sensorQuadEncoder)
#pragma config(Motor,  port1,           INTAKE,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           DRIVE_R,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           DRIVE_L,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           ANGLE,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           SLIDE_L,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           SLIDE_R,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           TREAD,         tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define   PRACTICE // If not defined, then competition mode
#include "VEX_Definitions.c"
#include "VEX_Declarations.c"
#include "VEX_OtherFunctions.c"
#include "VEX_Initialize.c"
#include "VEX_InputAndOutput.c"
#include "VEX_Autonomous.c"


task main()
	{
	initialize(BLUE_S); //Which way does the robot start pointing?
	autoReset(0); // 0 = Start, 1 = Finish

	//Drv Type,	Left,	Right,	Lift,	Dump,	Intake,	End type,	Action	//START AT RED HANGING ZONE

	//auto(SPD, 0,		0,		L_RCH2,	0,		0,		TIME_LIMIT,	2000);	//wait
	/*auto(GYRO2, -900,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn
	auto(STR,	0,		200,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Straight
	auto(STR,	0,		2000,	L_RCH2,	0,		0,		DRIV_READY,	NEXT);	//Straight*/

	auto(GYRO2, TURN_R,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn
	auto(STR,	HANG_Z,	770,	L_INTK,	0,		FWD,	DRIV_READY,	NEXT);	//Straight
	auto(STR,	HANG_Z,	-1500,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Reverse
	auto(STR,	HANG_Z,	-950,	L_GOA2,	0,		0,		DRIV_READY,	NEXT);	//Reverse + WHACK-BACK-1	5 pts
	auto(SPD,	0,		0,		L_DRIV,	0,		0,		TIME_LIMIT,	250);	//Wait (300 is reliable)
	auto(STR,	HANG_Z,	-970,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Reverse
	auto(GYRO2, -1100,	FULL,	L_GOAL,	0,		0,		DRIV_READY,	PID);	//Turn + Lift
	auto(STR,	700,	980,	L_GOAL,	0,		0,		DRIV_READY,	NEXT);	//Forward + Lift
	auto(GYRO2, 200,	FULL,	L_GOA2,	-100,	0,		DRIV_READY,	PID);	//Align
	auto(SPD,	0,		0,		L_GOA2,	REV,	0,		TIME_LIMIT,	2500);	//Dump - 1st double red		10 pts

	auto(STR,	BLUE_S,	-700,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Reverse
	auto(GYROL, TURN_R,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn + Drop
	auto(STR,	HANG_Z,	1250,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward + Drop
	auto(STR,	HANG_Z,	250,	L_INTK,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab
	auto(STR,	HANG_Z,	600,	L_RCH1,	REV,	0,		DRIV_READY,	NEXT);	//Forward over bump
	auto(STR,	HANG_Z,	250,	L_RCH2,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab
	auto(STR,	HANG_Z,	-300,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Backward
	auto(GYROL,	-50,	REV,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Align
	auto(STR,	1750,	-2000,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(GYROR,	50,		REV,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Align
	auto(STR,	HANG_Z,	-500,	L_GOA2,	REV,	0,		DRIV_READY,	PID);	//Backward and lift
	auto(SPD,	0,		0,		L_GOA2,	REV,	0,		TIME_LIMIT,	2700);	//Dump - 2nd double red		10 pts


	auto(STR,	HANG_Z,	600,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward and drop
	auto(GYRO2,	-200,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward the 2 Reds
	auto(STR,	1600,	2000,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab Reds
	auto(STR,	1600,	-1850,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Reverse
	auto(GYROR,	200,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn to align
	auto(STR,	HANG_Z,	-650,	L_GOA2,	-50,	0,		DRIV_READY,	NEXT);	//Backward + Lift [was time]
	auto(SPD,	0,		0,		L_GOA2,	REV,	0,		TIME_LIMIT,	1100);	//Dump - one red			5 pts

	// 1/2 goals full, 1 large ball down

	auto(STR,	HANG_Z,	245,	L_GOA2,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(GYRO2,	TURN_L,	FULL,	L_GOA2,	0,		0,		DRIV_READY,	PID);	//Turn toward other goal
	auto(STR,	BLUE_S,	2500,	L_GOA2,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(STR,	BLUE_S,	2000,	L_GOA2,	0,		0,		ONE_EDG_LN,	NEXT);	//Forward until line
	auto(STR,	BLUE_S,	170,	L_GOA2,	-50,	0,		DRIV_READY,	NEXT);	//Forward
	auto(SPD,	0,		0,		L_GOA2,	REV,	0,		TIME_LIMIT,	1000);	//Dump - other red			5 pts

	auto(STR,	BLUE_S,	200,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Forward
	auto(GYRO2,	TURN_R,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward Blue buckies
	auto(STR,	HANG_Z,	1500,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(STR,	HANG_Z,	400,	L_INTK,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab
	auto(STR,	HANG_Z,	650,	L_DRIV,	FWD,	0,		DRIV_READY,	NEXT);	//Forward over bump + Rotate
	auto(STR,	HANG_Z,	300,	L_RCH2,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab
	auto(STR,	HANG_Z,	-2300,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(STR,	HANG_Z,	-700,	L_GOA2,	70,		0,		DRIV_READY,	NEXT);	//Backward + lift
	auto(SPD,	-20,	-20,	L_GOA2,	FWD,	0,		TIME_LIMIT,	2800);	//Dump - 1st double blue	10 pts

	auto(STR,	HANG_Z,	1500,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward and drop
	auto(GYROL,	300,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward buckies
	auto(STR,	2100,	1050,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab Blues
	auto(STR,	2100,	-950,	L_GOAL,	0,		0,		DRIV_READY,	NEXT);	//Back away
	auto(SPD,	0,		0,		L_WHBK,	0,		0,		TIME_LIMIT,	500);	//WHACK-BACK-2				5 pts
	auto(GYROL,	-300,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward goal
	auto(STR,	HANG_Z,	-800,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(STR,	HANG_Z,	-750,	L_GOA2,	60,		0,		DRIV_READY,	NEXT);	//Backward + Lift
	auto(SPD,	-20,	-20,	L_GOA2,	FWD,	0,		TIME_LIMIT,	2800);	//Dump - 2nd double blue	10 pts

	auto(STR,	HANG_Z,	1500,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward + Drop
	auto(GYROL,	450,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Turn 45
	auto(STR,	2250,	1170,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward into blue bucky
	auto(GYROR,	450,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Turn 45
	auto(STR,	RED_S,	920,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(GYROR,	TURN_L,	FULL,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Turn into red bucky
	auto(GYROL,	-200,	FULL,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Turn more
	auto(STR,	1600,	-1500,	L_CAT3,	0,		0,		DRIV_READY,	NEXT);	//Backward past bump
	auto(STR,	1600,	-200,	L_CAT3,	0,		REV,	DRIV_READY,	NEXT);	//Backward past bump
	auto(GYROR,	-250,	FULL,	L_CAT3,	0,		REV,	DRIV_READY,	NEXT);	//Turn + Dump (No Large)	4 pts

	auto(STR,	1350,	400,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(GYROL,	450,	FULL,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Turn
	auto(STR,	HANG_Z,	880,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward over bump
	auto(STR,	HANG_Z,	1000,	L_CAT1,	0,		FWD,	DRIV_READY,	NEXT);	//Forward into red ball
	auto(STR,	HANG_Z,	-1800,	L_CAT2,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(STR,	HANG_Z,	-400,	L_CAT3,	0,		0,		DRIV_READY, NEXT);	//WHACK-BACK-4				10 pts
	auto(SPD,	0,		0,		L_CAT3,	0,		REV,	TIME_LIMIT,	800);	//Dump						4 pts

	auto(GYROR,	-450,	FULL,	L_CAT2,	0,		0,		DRIV_READY,	NEXT);	//Turn
	auto(STR,	1350,	750,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(GYROL,	650,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Turn
	auto(STR,	HANG_Z,	900,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward over bump
	auto(STR,	HANG_Z,	700,	L_CAT1,	0,		FWD,	DRIV_READY,	NEXT);	//Forward into large blue
	auto(STR,	HANG_Z,	-1700,	L_CAT2,	0,		0,		DRIV_READY,	NEXT);	//Backward past bump
	auto(GYROL,	250,	FULL,	L_CAT2,	0,		0,		DRIV_READY,	NEXT);	//Turn
	auto(STR,	2050,	-550,	L_CAT2,	0,		0,		DRIV_READY,	NEXT);	//Backward to barrier
	auto(STR,	2050,	-400,	L_CAT3,	0,		0,		DRIV_READY, NEXT);	//WHACK-BACK-5				10 pts
	auto(SPD,	0,		0,		L_CAT3,	0,		REV,	TIME_LIMIT, 800);	//Dump						4 pts

	// 2/2 goals full, 6 large balls and 4 buckies in goal zone, 2 sec remain, bot is too short to hang.
	autoReset(1);

	for (int j=0; j<10; j++)
		motor[j]=0;

	while(1==1) {}
	}


/* BUGS
LIFT_READY was not working correctly, triggered too soon; maybe working now.

dump 2 short 1st dble blue
1100 turn back up too far
then rev too far into bar

*/

/*
	auto(STR,	BLUE_S,	480,	L_INTK,	0,		FWD,	DRIV_READY,	NEXT);	//Straight + Grab
	auto(GYRO2, 300,	FULL,	L_DRIV,	0,		FWD,	DRIV_READY,	PID);	//Turn toward red bucky
	auto(STR,	1200,	300,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward into red bucky
	auto(STR,	1350,	-400,	L_INTK,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(GYRO2,	450,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn Into 1st Red Bucky
	auto(STR,	HANG_Z,	-1200,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward under bridge
	auto(STR,	HANG_Z,	-900,	L_GOA2,	-40,	0,		DRIV_READY,	PID);	//Backward and lift
	auto(SPD,	0,		0,		L_GOA2,	REV,	0,		TIME_LIMIT,	2500);	//Dump - 2nd double red

	auto(STR,	HANG_Z,	1400,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward and drop
	auto(GYRO2,	-350,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward buckies
	auto(STR,	1450,	1400,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward into buckies
	auto(STR,	1450,	-1350,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward away from bump
	auto(GYROR,	350,	REV,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward goal
	auto(STR,	HANG_Z,	-500,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(STR,	HANG_Z,	-700,	L_GOA2,	-40,	0,		DRIV_READY,	PID);	//Backward and lift
	auto(SPD,	0,		0,		L_GOA2,	REV,	0,		TIME_LIMIT,	2600);	//Dump - 3rd double red
*/
