#pragma config(Sensor, in1,    LINE_L,         sensorReflection)
#pragma config(Sensor, in2,    LINE_C,         sensorReflection)
#pragma config(Sensor, in3,    LINE_R,         sensorReflection)
#pragma config(Sensor, in5,    ANGLE_POT,      sensorPotentiometer)
#pragma config(Sensor, in6,    GYRO,           sensorGyro)
#pragma config(Sensor, dgtl1,  QUAD_R,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  QUAD_L,         sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  ULTRA,          sensorSONAR_cm)
#pragma config(Sensor, dgtl11, QUAD_SLIDE,     sensorQuadEncoder)
#pragma config(Motor,  port1,           INTAKE,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           DRIVE_R,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           DRIVE_L,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           ANGLE,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           SLIDE_L,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           SLIDE_R,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           TREAD,         tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define   MAIN_FILE
#define   PRACTICE // If not defined, then competition mode
#include "VEX_Definitions.c"
#include "VEX_Declarations.c"
#include "VEX_OtherFunctions.c"
#include "VEX_Initialize.c"
#include "VEX_InputAndOutput.c"
#include "VEX_Autonomous.c"

#define RUN   RUN_ALL // RUN_ALL, RUN_HALF, RUN_END

task main()
	{
#if (RUN==RUN_ALL)
	initialize(BLUE_S); //Which way does the robot start pointing?
	autoReset(0); // 0 = Start, 1 = Finish
	//Drv Type,	Left,	Right,	Lift,	Dump,	Intake,	End type,	Action	//START AT RED HANG ZONE
	auto(STR,	BLUE_S,	280,	L_INTK,	0,		FWD,	DRIV_READY,	NEXT);	//Straight + Grab
	auto(GYRO2,	TURN_L,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn Left
	auto(STR,	GOAL_Z,	700,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward onto bump
	auto(SPD,	0,		0,		L_DRIV,	0,		FWD,	TIME_LIMIT,	200);	//Wait + Grab
	auto(STR,	GOAL_Z,	300,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab
	auto(STR,	GOAL_Z,	1600,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward under bridge
	auto(STR,	GOAL_Z,	1000,	L_GOAL,	40,		0,		DRIV_READY,	PID);	//Forward and lift
	auto(SPD,	0,		0,		L_GOAL,	FWD,	1,		TIME_LIMIT,	2800);	//Dump - 1st double red

	auto(STR,	GOAL_Z,	-200,	L_GOAL,	0,		0,		DRIV_READY,	NEXT);	//Reverse
	auto(STR,	GOAL_Z,	-1400,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Reverse and drop
	auto(GYRO2,	1500,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward buckies
	auto(STR,	1500,	1150,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward toward buckies
	auto(STR,	1500,	-1100,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward away from buckies
	auto(GYROR,	300,	REV,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward goal
	auto(STR,	HANG_Z,	-1000,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(STR,	HANG_Z,	-600,	L_GOA2,	-40,	0,		DRIV_READY,	PID);	//Backward and lift
	auto(SPD,	0,		0,		L_GOA2,	REV,	0,		TIME_LIMIT,	2600);	//Dump - 2nd double red

	auto(STR,	HANG_Z,	1650,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward and drop
	auto(SPD,	0,		0,		L_WHBK,	0,		0,		TIME_LIMIT,	1000);	//WHACK-BACK-1
	auto(STR,	HANG_Z,	250,	L_GOAL,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(GYRO2,	TURN_L,	FULL,	L_GOAL,	0,		0,		DRIV_READY,	PID);	//Turn toward 2nd large
	auto(STR,	BLUE_S,	1140,	L_GOAL,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(GYRO2,	TURN_R,	FULL,	L_GOAL,	0,		0,		DRIV_READY,	PID);	//Align with 2nd large
	auto(STR,	HANG_Z,	-390,	L_WHBK,	0,		0,		TIME_LIMIT,	600);	//WHACK-BACK-2
	auto(STR,	HANG_Z,	0,		L_DRIV,	0,		0,		TIME_LIMIT,	500);	//drop Lift
	auto(STR,	HANG_Z,	1000,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab Red
	auto(GYROL,	TURN_L,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward blue tiles
	auto(STR,	BLUE_S,	730,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(GYROL,	TURN_R,	FULL,	L_DRIV,	0,		FWD,	DRIV_READY,	PID);	//Turn + Grab Blue
	auto(GYROR,	100,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Align with big ball
	auto(STR,	1900,	-1200,	L_WHBK,	0,		0,		TIME_LIMIT,	1600);	//WHACK-BACK-3
	auto(STR,	1900,	340,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward + drop
	auto(GYROL,	-450,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward goal
	auto(STR,	1450,	-1800,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward under bridge
	auto(GYROR,	350,	FULL,	L_GOA2,	0,		0,		DRIV_READY,	PID);	//Turn toward goal + Lift
	auto(SPD,	REV,	REV,	L_GOA2,	60,		0,		TIME_LIMIT,	300);	//Backward + Lift
	auto(SPD,	0,		0,		L_GOA2,	FWD,	0,		TIME_LIMIT,	1400);	//Dump - single red

	// 1/2 goals full, 2 large balls down

	auto(STR,	HANG_Z,	200,	L_GOA2,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(GYRO2,	TURN_L,	FULL,	L_GOA2,	0,		0,		DRIV_READY,	PID);	//Turn toward other goal
	auto(STR,	BLUE_S,	3000,	L_GOA2,	-60,	0,		ONE_EDG_LN,	NEXT);	//Forward until line
	auto(STR,	BLUE_S,	170,	L_GOA2,	-100,	0,		DRIV_READY,	NEXT);	//Forward
	auto(SPD,	0,		0,		L_GOA2,	REV,	0,		TIME_LIMIT,	1500);	//Dump - single blue

	auto(STR,	BLUE_S,	200,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Forward
	auto(GYRO2,	TURN_R,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward Blue buckies
#endif

#if (RUN==RUN_HALF)
	// The following portion is for tweaking the last half.
	// Start it in the blue middle zone.
	initialize(RED_S);
	autoReset(0);
	auto(SPD,	-20,	-20,	L_DRIV,	0,		0,		TIME_LIMIT,	1000);	//Straight + push
	auto(GYRO2,	TURN_L,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn Left
	auto(STR,	HANG_Z,	-555,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(ENC,	-650,	0,		L_DRIV,	0,		0,		DRIV_READY,	PID);	//Shift - 1
	auto(ENC,	0,		-650,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Shift - 2
	auto(STR,	HANG_Z,	-1000,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(GYRO2,	TURN_R,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward Blue goal
	auto(SPD,	0,		0,		L_DRIV,	0,		0,		TIME_LIMIT,	1000);	//Wait
	auto(GYRO2,	TURN_L,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward Blue Buckies
#endif
#if (RUN==RUN_ALL || RUN==RUN_HALF)
	auto(STR,	HANG_Z,	1500,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(STR,	HANG_Z,	800,	L_INTK,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab
	auto(STR,	HANG_Z,	550,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward over bump
	auto(STR,	HANG_Z,	350,	L_INTK,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab
	auto(STR,	HANG_Z,	-2850,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(STR,	HANG_Z,	-400,	L_GOA2,	40,		0,		DRIV_READY,	NEXT);	//Backward + lift
	auto(SPD,	-20,	-20,	L_GOA2,	FWD,	0,		TIME_LIMIT,	2800);	//Dump - 1st double blue

	auto(STR,	HANG_Z,	1500,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward and drop
	auto(GYROL,	300,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward buckies
	auto(STR,	2100,	950,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab Blue
	auto(STR,	2100,	-950,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Back away
	auto(GYROL,	-300,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward goal
	auto(STR,	HANG_Z,	-850,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(STR,	HANG_Z,	-600,	L_GOA2,	60,		0,		DRIV_READY,	NEXT);	//Backward + Lift
	auto(SPD,	-20,	-20,	L_GOA2,	FWD,	0,		TIME_LIMIT,	2650);	//Dump - 2nd double blue
#endif

#if (RUN==RUN_END)
	// The following portion is for tweaking the very end.
	// Start it in the blue middle zone.
	initialize(RED_S);
	autoReset(0);
	auto(STR,	RED_S,	270,	L_DRIV,	0,		REV,	DRIV_READY,	NEXT);	//Straight + push
	auto(GYRO2,	TURN_L,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn Left
	auto(STR,	HANG_Z,	-2400,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward
#endif
#if (RUN==RUN_ALL || RUN==RUN_HALF || RUN==RUN_END)
	auto(GYROR,	-400,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Turn - Align 1
	auto(GYROL,	400,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Turn - Align 2
	auto(STR,	HANG_Z,	1350,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward + Drop
	auto(SPD,	0,		0,		L_WHBK,	0,		0,		TIME_LIMIT,	1000);	//WHACK-BACK-4
	auto(STR,	HANG_Z,	1800,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward + Drop
	auto(STR,	HANG_Z,	365,	L_INTK,	FWD,	FWD,	DRIV_READY,	NEXT);	//Forward + Grab
	auto(SPD,	0,		0,		L_INTK,	FWD,	0,		TIME_LIMIT,	500);	//Wait
	auto(STR,	HANG_Z,	315,	L_INTK,	FWD,	FWD,	DRIV_READY,	NEXT);	//Forward + Grab
	auto(STR,	HANG_Z,	-550,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward beside
	auto(GYROR,	TURN_R,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn 90
	auto(STR,	RED_S,	950,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward in front of ball
	auto(GYRO2,	TURN_L,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn 90
	auto(STR,	HANG_Z,	900,	L_CAT1,	0,		0,		DRIV_READY,	NEXT);	//Forward into ball
	auto(STR,	HANG_Z,	-2200,	L_CAT2,	0,		0,		DRIV_READY,	NEXT);	//Backward to barrier
	auto(SPD,	0,		0,		L_CAT3,	0,		0,		TIME_LIMIT,	1500);	//Catapult
	auto(SPD,	0,		0,		L_CAT3,	0,		REV,	TIME_LIMIT,	1000);	//Dump

	// 2/2 goals full, 4 large balls down, 16 sec remain, bot is too short to hang.
	autoReset(1);
#endif

	while(1==1)
		{
		zeroMotors();
		output();
		wait1Msec(10);
		}
	}

/* BUGS

LIFT_READY was not working correctly, triggered too soon; maybe working now.

*/
