#pragma config(Sensor, in1,    LINE_L,         sensorReflection)
#pragma config(Sensor, in2,    LINE_C,         sensorReflection)
#pragma config(Sensor, in3,    LINE_R,         sensorReflection)
#pragma config(Sensor, in5,    ANGLE_POT,      sensorPotentiometer)
#pragma config(Sensor, in6,    GYRO,           sensorGyro)
#pragma config(Sensor, dgtl1,  QUAD_R,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  QUAD_L,         sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  ULTRA,          sensorSONAR_cm)
#pragma config(Sensor, dgtl11, QUAD_SLIDE,     sensorQuadEncoder)
#pragma config(Motor,  port1,           INTAKE,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           DRIVE_R,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           DRIVE_L,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           ANGLE,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           SLIDE_L,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           SLIDE_R,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           TREAD,         tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Definitions.c"
#define   PRACTICE // If not defined, then competition mode
#include "Declarations.c"
#include "OtherFunctions.c"
#include "Initialize.c"
#include "InputAndOutput.c"
#include "Autonomous.c"

task main()
	{
	initialize();
	autoReset(0);

	//Drv Type,	Left,	Right,	Lift,	Dump,	Intake,	End type,	Action	//START AT RED HANG ZONE
	auto(STR,	BLUE_S,	270,	L_INTK,	0,		FWD,	DRIV_READY,	NEXT);	//Straight + Grab
	auto(GYRO2,	TURN_L,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn Left
	auto(STR,	GOAL_Z,	700,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward onto bump
	auto(SPD,	0,		0,		L_DRIV,	0,		FWD,	TIME_LIMIT,	200);	//Wait + Grab
	auto(STR,	GOAL_Z,	300,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab
	auto(STR,	GOAL_Z,	1600,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward under bridge
	auto(STR,	GOAL_Z,	1030,	L_GOAL,	40,		0,		DRIV_READY,	PID);	//Forward and lift
	auto(SPD,	0,		0,		L_GOAL,	FWD,	0,		TIME_LIMIT,	2800);	//Dump - 1st double red

	auto(STR,	GOAL_Z,	-200,	L_GOAL,	0,		0,		DRIV_READY,	NEXT);	//Reverse
	auto(STR,	GOAL_Z,	-1600,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Reverse and drop
	auto(GYRO2,	1350,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward buckies
	auto(STR,	1350,	750,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward toward buckies
	auto(GYROL,	450,	FULL,	L_DRIV,	0,		FWD,	DRIV_READY,	PID);	//Turn into 2 red buckies
	auto(GYROL,	-450,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn back
	auto(STR,	1350,	-650,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward toward goal
	auto(GYROR,	450,	REV,	L_DRIV,	0,		FWD,	DRIV_READY,	PID);	//Turn toward goal
	auto(STR,	HANG_Z,	-1000,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Reverse
	auto(STR,	HANG_Z,	-600,	L_GOA2,	0,		0,		DRIV_READY,	PID);	//Reverse and lift
	auto(SPD,	0,		0,		L_GOA2,	REV,	0,		TIME_LIMIT,	3000);	//Dump - 2nd double red

	auto(STR,	HANG_Z,	1650,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Forward and drop
	auto(SPD,	0,		0,		L_WHBK,	0,		0,		TIME_LIMIT,	1000);	//WHACK-BACK-1
	auto(STR,	HANG_Z,	250,	L_GOAL,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(GYROR,	TURN_L,	FULL,	L_GOAL,	0,		0,		DRIV_READY,	PID);	//Turn toward 2nd large
	auto(STR,	BLUE_S,	640,	L_GOAL,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(GYRO2,	TURN_R,	FULL,	L_GOAL,	0,		0,		DRIV_READY,	PID);	//Align with 2nd large
	auto(STR,	HANG_Z,	-780,	L_WHBK,	0,		0,		DRIV_READY,	NEXT);	//WHACK-BACK-2
	auto(STR,	HANG_Z,	0,		L_DRIV,	0,		0,		TIME_LIMIT,	500);	//drop Lift
	auto(STR,	HANG_Z,	1000,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab Red
	auto(GYROL,	TURN_L,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward blue tiles
	auto(STR,	BLUE_S,	1010,	L_DRIV,	100,	0,		DRIV_READY,	PID);	//Forward
	auto(GYROL,	TURN_R,	FULL,	L_DRIV,	0,		FWD,	DRIV_READY,	PID);	//Turn + Grab Blue
	auto(GYROR,	100,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn to big ball
	auto(STR,	1900,	-1200,	L_WHBK,	0,		0,		DRIV_READY,	NEXT);	//WHACK-BACK-3
	auto(STR,	1900,	340,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward + drop
	auto(GYROL,	-550,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn 20 deg toward goal
	auto(STR,	1350,	-1480,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward under bridge
	auto(GYROR,	450,	FULL,	L_GOA2,	0,		0,		DRIV_READY,	PID);	//Turn toward goal
	auto(STR,	HANG_Z,	-700,	L_GOA2,	0,		0,		DRIV_READY,	NEXT);	//Backward and lift
	auto(SPD,	-20,	-20,	L_GOA2,	FWD,	0,		TIME_LIMIT,	1600);	//Dump - single red

	// 1/2 goals full, 2 large balls down

	auto(STR,	HANG_Z,	200,	L_GOA2,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(GYRO2,	TURN_L,	FULL,	L_GOA2,	0,		0,		DRIV_READY,	PID);	//Turn toward other goal
	auto(SPD,	100,	100,	L_GOA2,	-60,	0,		ONE_EDG_LN,	NEXT);	//Forward
	auto(STR,	BLUE_S,	170,	L_GOA2,	0,		0,		DRIV_READY,	PID);	//Forward
	auto(SPD,	0,		0,		L_GOA2,	REV,	0,		TIME_LIMIT,	1700);	//Dump - single blue

	auto(STR,	BLUE_S,	370,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Forward
	auto(GYRO2,	TURN_R,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward Blue buckies
	auto(STR,	HANG_Z,	1600,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Forward
	auto(STR,	HANG_Z,	600,	L_INTK,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab
	auto(STR,	HANG_Z,	850,	L_DRIV,	-100,	FWD,	DRIV_READY,	PID);	//Forward over bump
	auto(STR,	HANG_Z,	150,	L_DRIV,	0,		FWD,	DRIV_READY,	PID);	//Forward over bump
	auto(STR,	HANG_Z,	-2690,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Back up fully
	auto(GYROL,	-250,	FULL,	L_GOA2,	0,		0,		DRIV_READY,	PID);	//Shift beside goal + Lift
	auto(STR,	1550,	-120,	L_GOA2,	FWD,	0,		DRIV_READY,	NEXT);	//Backward + dump
	auto(GYROR,	250,	FULL,	L_GOA2,	0,		0,		DRIV_READY,	PID);	//Shift beside goal
	auto(SPD,	-20,	-20,	L_GOA2,	FWD,	0,		TIME_LIMIT,	3300);	//Dump - 1st double blue

	auto(STR,	HANG_Z,	1580,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Forward and drop
	auto(GYROL,	450,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward buckies
	auto(STR,	2250,	600,	L_DRIV,	0,		FWD,	DRIV_READY,	NEXT);	//Forward + Grab Blue
	auto(GYROR,	-450,	FULL,	L_DRIV,	0,		FWD,	DRIV_READY,	PID);	//Turn into buckies
	auto(GYROR,	450,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn away
	auto(STR,	2250,	-600,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Back away
	auto(GYROL,	-450,	FULL,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Turn toward goal
	auto(STR,	HANG_Z,	-920,	L_DRIV,	0,		0,		DRIV_READY,	NEXT);	//Backward
	auto(STR,	HANG_Z,	-500,	L_GOA2,	0,		0,		DRIV_READY,	PID);	//Backward + Lift
	auto(SPD,	-20,	-20,	L_GOA2,	FWD,	0,		TIME_LIMIT,	3300);	//Dump - 2nd double blue

	auto(STR,	HANG_Z,	1650,	L_DRIV,	0,		0,		DRIV_READY,	PID);	//Forward and drop
	auto(SPD,	0,		0,		L_WHBK,	0,		0,		TIME_LIMIT,	1000);	//WHACK-BACK-4

	// 2/2 goals full, 4 large balls down, 8 sec remain, too short to hang.
	autoReset(1);
	}

/* BUGS

LIFT_READY was not working correctly, triggered too soon; maybe working now.

GYRO_R is needs reversed input
*/
